### ISSUE TITLE
Wording of error msg

### ISSUE THREAD

**Issue by yamaguchih** [longlho/node-jsonrpc#1]
In jrpc.js, the error raised when a method handler is not found, or the handler doesn't have the method requested, the error message is unclear and should be changed. ("Has but doesn't have")

```
if (!handler || !handler.hasOwnProperty(methodArr[1]))
return _generateError(reqId, 'Method Not Found', handler + " has but doesn't have " + jsonRequest.method);
```

**Comment by longlho** [comment]
Lol that was for debugging, u can take that off.

Long Ho
Software Engineer
Selerity Corp

**Comment by yamaguchih** [comment]
So the whole if statement is unnecessary?

**Comment by longlho** [comment]
not the whole if statement, just the error message.

It actually returns a valid JSON-RPC error mess
