### ISSUE TITLE
Allow registering a JSON object?

### ISSUE THREAD

**Issue by yamaguchih** [longlho/node-jsonrpc#2]
In the register function, currently only a single handler / array of handlers is allowed. Would it be difficult to allow a JSON map of format 

{
  HandlerA: (object)
  HandlerB: (object)
}

to be registered?

**Comment by longlho** [comment]
hmm definitely possible. The key has to be extracted from handler.name for API consistency though. What is the specific use case for this since handlers r singletons and only used to register API calls, storing a map doesn't seem to be necessary

**Comment by yamaguchih** [comment]
I guess it wouldn't be really useful and would be annoying to create the map in the first place. It was just a thought...

Right now metadb-core server.js is doing it using array literal
var handlers = [  
                       (require('./models/handlers/AuthenticationHandler')), 
                       (require('./models/handlers/VocabHandler'))  
                     ];
njrpc.register( handlers );

which seems to work fine.
